# Generated by Django 5.2 on 2025-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('DC', 'Dc'), ('Marvel', 'Marvel'), ('SHUEISHA', 'Shueisha')], max_length=20)),
                ('description', models.TextField()),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('rent_price', models.IntegerField(default=7)),
            ],
        ),
    ]
