# Generated by Django 5.1.6 on 2025-05-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_customerdetail_order_publisher_rental_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='comic_image',
            field=models.ImageField(null=True, upload_to='comic_images'),
        ),
    ]
